### ISSUE TITLE
This doesn't build anymore.

### ISSUE THREAD

**Issue by TomCrowley** [cgfrost/cf-sample-app-nodejs#2]
I really need a good sample CF node app.

 Resolving node version 5.* via semver.io...
       Downloading and installing node undefined...
       Downloaded []
       Unable to download node undefined; does it exist?
-----> Build failed

**Comment by TomCrowley** [comment]
Sorry, it's been a long day. Just getting rid of "engines" makes it work.

**Comment by cgfrost** [comment]
Yeah, the dependencies are a little out of date as well.

What version of the NodeJS buildpack are you using, I'm guessing the standard release isn't up to 5.* yet.

**Comment by cgfrost** [comment]
Should be fixed with commit 1891d88064a2501116625760aef720ed36d15e84
